// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CollabAgentRef = {
/**
 * Thread ID of the receiver/new agent.
 */
threadId: string,
/**
 * Optional nickname assigned to an AgentControl-spawned sub-agent.
 */
agentNickname?: string | null,
/**
 * Optional role (agent_role) assigned to an AgentControl-spawned sub-agent.
 */
agentRole?: string | null, };
