// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConfiguredHookConditions = { profile: string | null, profiles: Array<string>, model: string | null, models: Array<string>, permissionMode: string | null, permissionModes: Array<string>, };
